jobs:
  include:
    - language: python
      name: platformio CI
      python: 3.9
      install:
        - cd esp32
        - pip install -U platformio
        - pio update
      script:
        # example BuildConfig.h
        - echo '#define WIFI_SSID ""' >> include/BuildConfig.h
        - echo '#define WIFI_PASSWORD ""' >> include/BuildConfig.h
        - echo '#define API_ENDPOINT ""' >> include/BuildConfig.h

        - pio ci --project-conf=platformio.ini --lib="." .

    - language: python
      name: backend (python)
      python: 3.9
      install:
        - pip install flake8 black --upgrade
      script:
        - black --check backend/
        - cd backend && flake8 .

    - language: node_js
      name: frontend (JS)
      node_js: 12
      install:
        - npm install --global prettier
      script:
        - cd frontend && prettier --check .
