version: "3.8"

services:
  redis:
    image: redis
    container_name: remote_door_lock_redis

  app:
    image: prytz/remote-door-lock
    environment:
      REDIS_HOST: "redis"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      FRONTEND_URL: "${FRONTEND_URL}"
      BACKEND_URL: "${BACKEND_URL}"
      OAUTHLIB_INSECURE_TRANSPORT: "${OAUTHLIB_INSECURE_TRANSPORT}"
      PORT: "${PORT}"
      DATABASE_TYPE: "sqlite"
      INSECURE: "${INSECURE}"
      TZ: "${TZ}"
    depends_on:
      - redis
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"
    container_name: remote_door_lock_app
    volumes:
      - ${DATABASE_PATH}:/var/www/app/database
