version: '3.8'

services:
    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: 'remote-door-lock'
            MYSQL_USER: 'remote-door-lock'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - 3306:3306
        expose:
            - 3306
    redis:
        image: redis
        ports:
            - 6379:6379
        expose:
            - 6379
